//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZDVApps.Services.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OU=Approval,OU=AppV5,OU=GRP,OU=AppvUser,DC=Uni-Mainz,DC=DE")]
        public string ActiveDirectoryContainerApproval {
            get {
                return ((string)(this["ActiveDirectoryContainerApproval"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OU=Selfservice,OU=AppV5,OU=GRP,OU=AppvUser,DC=Uni-Mainz,DC=DE")]
        public string ActiveDirectoryContainerSelfService {
            get {
                return ((string)(this["ActiveDirectoryContainerSelfService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OU=AppvUser,DC=Uni-Mainz,DC=DE")]
        public string ActiveDirectoryContainerUsers {
            get {
                return ((string)(this["ActiveDirectoryContainerUsers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OU=AppV5,OU=GRP,OU=AppvUser,DC=Uni-Mainz,DC=DE")]
        public string ActiveDirectoryContainerAppVGroups {
            get {
                return ((string)(this["ActiveDirectoryContainerAppVGroups"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OU=MA,OU=UserPSC,OU=AppvUser,DC=Uni-Mainz,DC=DE")]
        public string ActiveDirectoryContainerEmployee {
            get {
                return ((string)(this["ActiveDirectoryContainerEmployee"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OU=AppV5,OU=GRP,OU=AppvUser,DC=Uni-Mainz,DC=DE")]
        public string ActiveDirectoryContainerAppVPackages {
            get {
                return ((string)(this["ActiveDirectoryContainerAppVPackages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DC=Uni-Mainz,DC=DE")]
        public string ActiveDirectoryGlobalContainer {
            get {
                return ((string)(this["ActiveDirectoryGlobalContainer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppvPackages_AllPackages {
            get {
                return ((string)(this["AppvPackages_AllPackages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://appv5:2500/Packages")]
        public string API_Appv {
            get {
                return ((string)(this["API_Appv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\appv5_packages.xml")]
        public string API_Appv_File {
            get {
                return ((string)(this["API_Appv_File"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADUsers")]
        public string UsersPackagesRegion {
            get {
                return ((string)(this["UsersPackagesRegion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADGroupsRegion")]
        public string ADGroupsRegion {
            get {
                return ((string)(this["ADGroupsRegion"]));
            }
        }
    }
}
